### ISSUE TITLE
uMod stopped working

### ISSUE THREAD

**Issue by burgergit** [gwdevhub/Daybreak#765]
Played yesterday through Daybreak with uMod enabled. Everything worked perfectly.
Wanted to play today but the uMod mods don't load. Tried multiple times.

**Comment by AlexMacocian** [comment]
Did this happen after the update?

**Comment by burgergit** [comment]
Yes I think so.

**Comment by AlexMacocian** [comment]
So there's a 'bug' with the GW updater as it's not made to maintain more than one exe per computer. 
What happens is that when an update happens, the GW updater starts and it searches for the executable it wants to update. If you have more than one GW executable, it will find one and update, which might not be the one you started.
Since it never updates the one you launch, on each start it'll trigger the update which then will start the second executable.


A solution would be to use the Download Guildwars button in Daybreak and overwrite the executable you want to launch. Once the download finishes, close Guildwars and start it again through Daybreak and it should work. I'd do this for all your executables to make sure they're up to date.

If the above solution doesn't work, I'd try to manually update/download all your executables. You can keep the GW.dat file as it is 

Let me know if the above solutions fixed your issue

**Comment by burgergit** [comment]
Thank you, will try today and let you know

**Comment by burgergit** [comment]
It worked! Thank you :)

**Comment by AlexMacocian** [comment]
#763 
Linked to an issue that should provide a permanent solution to this issue once implemented.

In the meantime, your problem will probably resurface on every update, so you'll have to repeat the steps above to correct it
